include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    must_be_immutable: ignore
  exclude:
    - lib/**/l10n/gen/*
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
linter:
  rules:
    public_member_api_docs: false
